# Detailed 7-day plans for weeks 5-24. Imported by _generate_weekly_readmes.py

def d(title, goal, learn, practice, analogy, ai, output, check, source=None):
    return dict(title=title, goal=goal, learn=learn, practice=practice, analogy=analogy, ai=ai, output=output, check=check, source=source or [])

DETAILED = {}

# Week 05
DETAILED[5] = dict(
    days=[
        d("BFF 模式与网关职责","理解 BFF 为何存在、网关与微服务边界。",
          ["阅读 BFF 模式与 Building Microservices 相关章节","理解 frontapi 与内网服务分工"],
          ["读 mall-gateway README","画 BFF 架构图：前端→网关→微服务","列出网关 5 项职责"],
          ["BFF≈专为前端定制的 API 层","网关≈Express 聚合层"],
          ["网关是否承担了不该承担的业务？"],["BFF 架构图","职责清单"],["能说明 BFF 价值","能区分网关与微服务"],["mall-gateway/common/BaseApi.php"]),
        d("HTTP 客户端封装","掌握 *Request 类如何转发到内网服务。",
          ["阅读 Yii2 HTTP Client 基础","阅读 Laravel HTTP Client 作对照"],
          ["读 PayRequest.php 全文","读 OrderRequest.php 并对比结构","解释 getBaseUrl() 与 path 拼接"],
          ["PayRequest≈axios.create({ baseURL })","BaseApi≈axios 实例基类"],
          ["封装层还应包含哪些能力？"],["PayRequest 笔记","OrderRequest 对比表"],["能解释 HTTP 封装","能说出 baseURL 配置位置"],["mall-gateway/services/http/PayRequest.php","mall-gateway/services/http/OrderRequest.php"]),
        d("薄 Controller 实践","理解网关 Controller 为何保持精简。",
          ["复习 Module 路由","找一个 PayController action 逐行分析"],
          ["统计 PayController 各 action 行数","手写一个「纯转发」action 伪代码","说明哪些逻辑不应出现在网关"],
          ["薄 Controller≈只做鉴权+取参+转发","业务逻辑≈下游微服务"],
          ["我设计的伪代码是否足够薄？"],["行数统计表","转发 action 伪代码"],["能解释「薄」的含义","能举反例"],["mall-gateway/frontapi/modules/Pay/controllers/PayController.php"]),
        d("鉴权、公参与反查链路","从前端 API 反查网关到内网完整路径。",
          ["阅读 AuthApiController 中 token 与公参注入","从 mall-pc 找一个支付 API"],
          ["反查 pay/pay/methods 完整链路","画路由链路图","标注鉴权与白名单"],
          ["公参注入≈middleware 统一设置 req.context","反查≈前端 devtools 追请求"],
          ["链路是否完整？白名单是否合理？"],["路由链路图","白名单初稿"],["能独立反查一条 API","能标注 Filter/鉴权"],["mall-gateway/frontapi/modules/AuthApiController.php"]),
        d("Laravel 对比与类比日","完成 Laravel Http vs *Request 对照与类比打卡。",
          ["阅读 Laravel HTTP Client 文档 2h","回顾 BFF 笔记"],
          ["写 1 页 Laravel Http:: vs *Request 对照","完成本周类比打卡"],
          ["Laravel Http::≈*Request 封装"],
          ["对照是否抓住关键差异？"],["对照笔记","类比打卡"],["完成对照","完成打卡"],[]),
        d("结账 API 路由表项目","输出至少 5 个结账相关 API 路由表。",
          ["明确路由表字段：前端URL、网关action、HTTP client、目标服务、备注"],
          ["完成 5+ API 路由表","自测能否根据表反查代码"],
          ["路由表≈API 地图"],
          ["路由表是否可用于 onboarding？"],["结账 API 路由表"],["覆盖 5 个 API","表结构清晰"],[]),
        d("验收与预习","验收本周并预习订单域。",
          ["对照验收标准","预习 OrderController"],
          ["勾选验收","写周总结","列订单域 3 个目标"],
          ["预习≈提前读下一章"],["准备好学订单吗？"],["周总结"],["完成验收","明确下周目标"],[]),
    ]
)

# Week 06
DETAILED[6] = dict(
    days=[
        d("OrderController 结构与 action","读懂订单 Controller 编排方式。",
          ["复习 Yii2 Controller 与 try/catch 模式","理解 endSuccess/endFail"],
          ["读 OrderController 结构","选 1 个 action 追踪到 Service","记录入参/出参/错误码"],
          ["OrderController≈Express router handler 集合","endSuccess≈res.json({code,data})"],
          ["action 里是否有多余业务逻辑？"],["OrderController 笔记"],["能追踪 1 个 action 全链路"],["order-api/controllers/OrderController.php"]),
        d("OrderService 业务编排","理解 Service 层职责与返回约定。",
          ["阅读 Service 层设计规范","理解 ['code','data','info'] 返回格式"],
          ["读 OrderService 前 200 行","列 5 个 public 方法及职责","画 Service 调用 Repository 关系"],
          ["OrderService≈NestJS Service","返回数组≈统一业务响应包装"],
          ["哪些逻辑应在 Service 而非 Controller？"],["Service 方法清单"],["能列出 5 个方法职责"],["mall-core/common/services/order/OrderService.php"]),
        d("OrderConfirmForm 参数校验","对照前端结账页理解 Form 校验。",
          ["复习 Yii2 Form rules/scenarios","打开 mall-pc 结账页"],
          ["读 OrderConfirmForm","列前端字段 vs Form rules 对照表","标注必填与错误码"],
          ["OrderConfirmForm≈后端 Joi schema","scenarios≈不同接口不同 schema"],
          ["校验失败前端如何展示？"],["字段对照表"],["能对照 10+ 字段"],["order-api/forms/OrderConfirmForm.php"]),
        d("分布式锁与防重复提交","理解 LockHandleRedis 使用场景。",
          ["阅读 Redis 分布式锁原理","找使用锁的 Controller action"],
          ["读 LockHandleRedis","解释为何下单需要锁","对比前端防重复点击"],
          ["LockHandleRedis≈Redis SET NX EX","防重复下单≈按钮 disabled + 后端锁"],
          ["锁粒度与超时是否合理？"],["锁使用场景笔记"],["能解释为何需要锁"],[]),
        d("订单状态机与类比日","画订单状态流转图并完成类比打卡。",
          ["读 OrderRepository STATUS_MAPPING","对照前端订单状态 badge"],
          ["画订单状态机图","完成类比打卡"],
          ["STATUS_MAPPING≈前端 statusMap 常量"],
          ["状态映射是否完整？"],["状态机图","类比打卡"],["能解释主要状态","完成打卡"],["mall-core/common/repositorys/order/OrderRepository.php"]),
        d("下单全链路时序图","追踪 trade/confirm → trade/place 并画图。",
          ["复习网关路由表","明确订单服务入口"],
          ["追踪 confirm 与 place 全链路","画时序图含网关+订单服务","标注每步入参出参"],
          ["时序图≈联调必备文档"],
          ["时序图是否遗漏异步步骤？"],["下单时序图"],["时序图完成","能口述链路"],[]),
        d("验收与预习","验收并预习支付域。",
          ["对照验收","预习 PayService"],
          ["勾选验收","写总结"],["准备好学支付吗？"],["周总结"],["完成验收"],[]),
    ]
)

# Week 07
DETAILED[7] = dict(
    days=[
        d("PayController 分类","理解 client/internal/outer 控制器分类。",
          ["复习支付域文档","理解三类 Controller 使用场景"],
          ["读 PayController","列全部 action 与 HTTP 方法","按 client/internal/outer 分类"],
          ["outer≈Webhook 无用户鉴权","internal≈内网服务互调"],
          ["分类是否合理？"],["PayController action 清单"],["能说出三类区别"],["pay-service/pay-api/controllers/PayController.php"]),
        d("PayService 与 processPayment Node 链","掌握支付核心 Node 流水线。",
          ["阅读责任链模式","理解 NodeExecutionEngine 概念"],
          ["读 PayService processPayment","列 4 个 Node 及职责","画 Node 顺序图"],
          ["Node 链≈Express middleware 管道","Context≈req.context 共享状态"],
          ["Node 失败时如何中断？"],["Node 顺序图"],["能列出 4 个 Node"],["pay-service/common/services/pay/PayService.php"]),
        d("PaymentFactory 渠道工厂","理解支付方式到 SDK 的映射。",
          ["阅读工厂模式","读 PaymentFactory 源码"],
          ["列所有支付渠道常量与 Service 类","画「支付方式→公司→SDK」映射表"],
          ["PaymentFactory≈策略注册表 handlers map"],
          ["新增渠道要改哪些地方？"],["渠道映射表"],["能解释工厂映射"],["pay-service/common/factory/payment/PaymentFactory.php"]),
        d("支付渠道 SDK 封装","理解前后端支付分工。",
          ["选读 StripeService 或 BraintreeService","阅读 Stripe PaymentIntent 文档"],
          ["列 SDK 封装了哪些第三方 API","对比前端 Stripe.js 与后端 SDK 分工"],
          ["前端 SDK≈收集卡信息","后端 SDK≈创建/确认 PaymentIntent"],
          ["敏感信息是否在前端处理？"],["SDK 分工笔记"],["能说明前后端分工"],[]),
        d("ProcessPaymentNode 与类比日","读 ProcessPaymentNode 并画 Context 数据流。",
          ["读 ProcessPaymentNode 源码","回顾 Node 链图"],
          ["画 Context 字段在各 Node 间传递图","完成类比打卡"],
          ["Context 传递≈middleware 间共享 req 对象"],
          ["Context 字段是否足够？"],["数据流图","类比打卡"],["能解释 Context 作用"],["pay-service/common/services/pay/nodes/pay/ProcessPaymentNode.php"]),
        d("支付状态机与渠道笔记","画支付状态机并写渠道映射笔记。",
          ["整理创建→确认→捕获→完成状态","结合 PaymentFactory 写渠道笔记"],
          ["画支付状态机图","写 1 页渠道映射笔记"],
          ["状态机≈订单/支付联调共同语言"],
          ["状态机是否覆盖异常状态？"],["状态机图","渠道笔记"],["能口述状态机"],[]),
        d("验收与预习","验收并预习 MQ/Webhook。",
          ["对照验收","预习 RabbitMQ"],
          ["勾选验收","写总结"],["准备好学异步吗？"],["周总结"],["完成验收"],[]),
    ]
)

# Week 08
DETAILED[8] = dict(
    days=[
        d("RabbitMQ 基础","理解 exchange、route_key、消息投递。",
          ["RabbitMQ 教程前 3 章","项目 MQ 配置说明"],
          ["读 RabbitMq.php 工具类","列项目中 2 个 MQ 使用场景","对比 BullMQ"],
          ["RabbitMq::send≈amqplib publish","MQ≈异步解耦"],
          ["消息丢失如何防范？"],["MQ 场景笔记"],["能解释 send 参数"],["mall-core/common/libraries/App/Utils/RabbitMq.php"]),
        d("Stripe Webhook 与验签","理解 Webhook 入口与验签流程。",
          ["Stripe Webhooks 官方指南","阅读 outer/StripeController"],
          ["读 Webhook Controller","画 Webhook 处理流程","列验签关键步骤"],
          ["Webhook≈stripe.webhooks.constructEvent()"],
          ["验签失败如何处理？"],["Webhook 流程图"],["能解释验签流程"],["pay-service/pay-api/controllers/outer/StripeController.php"]),
        d("退款幂等设计","分析 RefundVerifyNode 与 MQ 节点。",
          ["理解幂等性概念","阅读退款相关 Node"],
          ["读 RefundVerifyNode","读 AddRefundHandleMqNode","写 1 页退款幂等分析"],
          ["幂等≈Redis SET NX + 业务唯一键"],
          ["重复退款如何拦截？"],["幂等分析文档"],["能解释幂等设计"],[]),
        d("Docker 开发环境","配置 Docker 并进入 PHP 容器。",
          ["Docker 入门教程","本地环境说明文档"],
          ["启动 Docker 环境","进入 PHP 容器","在容器内查看日志"],
          ["Docker≈统一开发与部署环境"],
          ["容器与本地 PHP 差异？"],["Docker 操作笔记"],["能进入容器","能查看日志"],[]),
        d("Laravel Queue 对比与阶段总结","写 Queue vs RabbitMQ 对照，阶段②自评。",
          ["Laravel Queues + Events 文档","回顾 W5-W8 笔记"],
          ["写 Queue vs RabbitMQ 对照","完成阶段②自评"],
          ["Laravel Queue≈RabbitMQ 上层抽象"],
          ["对照准确吗？"],["Queue 对照","阶段总结"],["完成对照","完成阶段自评"],[]),
        d("结账全链路时序图（含 MQ）","画含 Webhook 与 MQ 的完整结账图。",
          ["合并 W5 路由表与 W6/W7 时序","补充异步步骤"],
          ["画完整结账时序图","标注 MQ 与 Webhook 触发点"],
          ["全链路图≈架构面试必备"],
          ["是否遗漏网关层 Webhook？"],["完整时序图"],["时序图含 MQ/Webhook"],[]),
        d("验收与预习","验收并预习用户服务。",
          ["对照验收","预习 UserController"],
          ["勾选验收","写总结"],["准备好学用户域吗？"],["周总结"],["完成验收"],[]),
    ]
)

# Weeks 09-24 - continue with same level of detail
for wk, days in {
9: [
 d("UserController 与 quickLogin","追踪用户登录入口。",
   ["复习用户域结构","理解 client/internal 控制器"],
   ["读 UserController","追踪 actionQuickLogin 全链路","记录 code/data/info"],
   ["quickLogin≈社交/快捷登录 API"],["链路完整吗？"],["登录链路笔记"],["能追踪 quickLogin"],["user-service/user-api/controllers/UserController.php"]),
 d("UserService 与 Redis 缓存","理解用户缓存读写与失效。",
   ["Redis 缓存策略","读 UserService getUserInfoByRedis"],
   ["读 UserDetailRedis","列缓存 key 规则","说明何时写入/失效"],
   ["UserDetailRedis≈ioredis 用户缓存封装"],["缓存失效策略合理吗？"],["缓存策略笔记"],["能说明失效策略"],["user-service/common/redis/user/UserDetailRedis.php"]),
 d("注册 Node 链","理解 RegisterService 与 nodes 目录。",
   ["复习 NodeExecutionEngine","读 RegisterService"],
   ["列出注册前 5 个 Node","画注册 Node 顺序图"],
   ["注册链≈多步 middleware"],["Node 顺序正确吗？"],["注册 Node 图"],["能列 5 个 Node"],["user-service/common/services/user/RegisterService.php"]),
 d("OAuth 第三方登录","理解社交登录回调流程。",
   ["OAuth 2.0 基础","浏览 login 相关 Service"],
   ["梳理 Google/Facebook 登录回调","对比前端社交登录 SDK"],
   ["OAuth≈Passport.js 策略"],["回调安全注意什么？"],["OAuth 流程笔记"],["能说明回调流程"],[]),
 d("JWT 与类比日","学习 JWT，对比 Session，完成打卡。",
   ["jwt.io 介绍","找 token 生成与验证代码"],
   ["对比 JWT vs Session","完成类比打卡"],
   ["JWT≈无状态 token"],["何时用 JWT？"],["JWT 笔记","类比打卡"],["能说明 JWT 用途"],[]),
 d("用户域总结项目","完成注册 Node 图与用户域总结。",
   ["整理本周笔记"],
   ["完善注册 Node 图","写 1 页用户域总结"],
   ["总结≈知识沉淀"],["总结是否可复用？"],["用户域总结"],["Node 图完成"],[]),
 d("验收与预习","验收并预习售后。",["预习 AfterSaleService"],["勾选验收","写总结"],["准备好学售后吗？"],["周总结"],["完成验收"],[]),
],
10: [
 d("AfterSaleService 概览","浏览售后核心 Service 结构。",
   ["理解售后域复杂度"],
   ["浏览 AfterSaleService","列 10 个 public 方法职责"],
   ["大 Service≈需策略模式拆分"],["复杂度体现在哪？"],["方法清单"],["能列 10 个方法"],["aftersale-service/common/services/AfterSaleService.php"]),
 d("processingType 策略模式","读 ReturnGoodsRefund 与 Reissue。",
   ["Strategy Pattern 资料"],
   ["读 ReturnGoodsRefund","读 Reissue","对比接口实现"],
   ["processingType≈switch 拆成 Strategy class"],["新增类型如何扩展？"],["策略对比表"],["能解释策略模式"],["aftersale-service/common/services/processingType/concrete/ReturnGoodsRefund.php"]),
 d("售后状态机","读 AfterSaleStatusEnum 并画图。",
   ["对比订单状态机"],
   ["读枚举","画售后状态流转图"],
   ["枚举≈TS enum"],["状态是否完备？"],["状态机图"],["能画状态流转"],["aftersale-service/common/enums/AfterSaleStatusEnum.php"]),
 d("Console 与 API 分工","理解 Console 批处理场景。",
   ["Yii Console 命令格式"],
   ["读 OmsController","理解 php yii controller/action","对比 API 入口"],
   ["Console≈node scripts/*.js"],["何时用 Console？"],["API vs Console 笔记"],["能区分分工"],["aftersale-service/console/controllers/OmsController.php"]),
 d("支付回调链路","读 actionPayPaidNotify 画时序图。",
   ["复习支付回调"],
   ["读支付回调到售后更新链路","画时序图","完成类比打卡"],
   ["事件驱动≈Webhook 触发下游"],["链路清晰吗？"],["回调时序图"],["能说明回调链路"],[]),
 d("售后流程图项目","选一个售后类型画完整流程。",
   ["选退货退款或补发"],
   ["画申请→审核→处理→完成流程图"],
   ["流程图≈业务 onboarding"],["流程是否遗漏分支？"],["售后流程图"],["流程图完成"],[]),
 d("验收与预习","验收并预习 ThinkPHP。",["预习 TP8 手册"],["勾选验收"],["准备好学 TP8 吗？"],["周总结"],["完成验收"],[]),
],
11: [
 d("ThinkPHP 8 架构","读 TP8 手册与 store-api README。",
   ["ThinkPHP 8 架构概览"],
   ["读 README","列目录职责","对比 Yii2 项目结构"],
   ["TP8≈另一套 PHP MVC"],["结构差异？"],["目录职责表"],["能说明 TP8 结构"],["store-api/README.md"]),
 d("StoreController 到 StoreService","追踪门店列表接口。",
   ["SMVC 分层"],
   ["读 StoreController index()","追踪到 StoreService list()"],
   ["StoreService≈NestJS Service"],["分层清晰吗？"],["CRUD 链路笔记"],["能追踪 list 链路"],["store-api/app/admin/controller/store/StoreController.php","store-api/app/common/service/store/StoreService.php"]),
 d("Validate scene 分组","理解 TP8 Validate 与 scene。",
   ["ThinkPHP 验证器文档"],
   ["读 OfflineStore Validate","理解 scene","对比 Yii2 Form"],
   ["Validate scene≈Zod pick()"],["scene 如何选？"],["Validate 笔记"],["能解释 scene"],["store-api/app/admin/validate/store/OfflineStore.php"]),
 d("Model 与 ModelJoin","理解复杂查询放置位置。",
   ["ThinkORM 基础"],
   ["读 OfflineStore Model","读一个 ModelJoin","说明为何联表不放 Service"],
   ["ModelJoin≈复杂查询封装"],["是否合理？"],["ModelJoin 笔记"],["能解释联表封装"],[]),
 d("Yii2 vs TP8 对比","写分层对比表并完成打卡。",
   ["回顾 Yii2 CSR"],
   ["写至少 5 项对比","读 InternalServiceHelper","完成类比打卡"],
   ["TP8 SMVC vs Yii2 CSR"],["对比准确吗？"],["对比表","类比打卡"],["完成 5 项对比"],["store-api/app/common/library/helper/InternalServiceHelper.php"]),
 d("store-api CRUD 项目","独立追踪一条 CRUD 并画图。",
   ["选门店或商品接口"],
   ["追踪完整 CRUD","画接口流程图"],
   ["CRUD 链路≈联调文档"],["链路完整吗？"],["CRUD 流程图"],["能独立追踪"],[]),
 d("验收与预习","验收并预习跨服务。",["预习 PayInternal"],["勾选验收"],["准备好串联全链路吗？"],["周总结"],["完成验收"],[]),
],
12: [
 d("PayInternal 跨服务调用","理解订单调支付的封装。",
   ["跨服务 HTTP 规范"],
   ["读 PayInternal","追踪一次 capture","记录 path/参数/返回"],
   ["PayInternal≈payServiceClient.post"],["为何禁止 Service 直接 HTTP？"],["capture 调用笔记"],["能追踪 capture"],["mall-core/common/api/PayInternal.php"]),
 d("InternalServiceHelper","理解门店如何调内网服务。",
   ["门店与核心服务关系"],
   ["读 InternalServiceHelper","列可调用服务"],
   ["Helper≈内网服务门面"],["门面模式价值？"],["服务清单"],["能列内网服务"],["store-api/app/common/library/helper/InternalServiceHelper.php"]),
 d("结账全链路复盘","画前端一次结账的完整时序图。",
   ["合并 W5-W8 成果"],
   ["画含网关/订单/支付/MQ 时序","标注每跳等价 Node 层"],
   ["全链路≈BFF+微服务"],["有遗漏吗？"],["结账全链路图"],["能标注每跳"],[]),
 d("Laravel DI 对比","写 Yii2 ::instance() vs Laravel Container。",
   ["Laravel Service Container"],
   ["写 DI 对照笔记","读各服务 README 补充边界"],
   ["::instance()≈容器单例"],["对照准确吗？"],["DI 对照笔记"],["完成对照"],[]),
 d("架构文档与类比日","输出全链路架构文档 v1。",
   ["架构文档模板"],
   ["写架构文档 v1","完成类比打卡","确保脱敏"],
   ["架构文档≈团队 onboarding"],["是否脱敏？"],["架构文档 v1"],["文档可公开"],[]),
 d("阶段③总结项目","完善架构文档并写阶段总结。",
   ["阶段自评"],
   ["完善文档","写阶段③总结"],
   ["阶段复盘≈里程碑"],["达到阶段目标吗？"],["阶段总结"],["完成阶段自评"],[]),
 d("验收与预习","验收并预习 FastAPI。",["预习 FastAPI"],["勾选验收"],["准备好学 AI 后端吗？"],["周总结"],["完成验收"],[]),
],
13: [
 d("FastAPI 入门","搭建项目并实现 /health。",
   ["FastAPI 教程前 5 章"],
   ["创建 llm-gateway 项目","实现 /health","对比 Express"],
   ["FastAPI≈Express/Fastify"],["项目结构合理吗？"],["项目骨架"],["/health 可访问"],["ai-lab/llm-gateway/app/main.py"]),
 d("多模型 /chat 接口","接入 OpenAI 与 Claude。",
   ["OpenAI/Anthropic API 文档"],
   ["实现 /chat 支持 model 参数","用 curl 测试两模型"],
   ["统一 Gateway≈多供应商抽象"],["切换模型如何实现？"],["/chat 接口"],["能切换 2 模型"],[]),
 d("Pydantic 请求验证","给 /chat 加请求体校验。",
   ["Pydantic 文档"],
   ["定义 ChatRequest model","校验 messages/model 字段"],
   ["Pydantic≈Zod"],["校验足够吗？"],["校验代码"],["非法请求被拒绝"],[]),
 d("错误处理与 API Key","加鉴权与统一错误格式。",
   ["FastAPI 异常处理"],
   ["实现 API Key 校验","统一错误响应"],
   ["API Key≈Bearer token"],["密钥如何管理？"],["错误处理代码"],["错误格式统一"],[]),
 d("类比日与测试","curl 测全部接口，完成打卡。",
   ["回顾 FastAPI 笔记"],
   ["测试全部接口","完成类比打卡","写 README"],
   ["FastAPI≈Express"],["接口设计问题？"],["测试记录","README"],["全部接口通过"],[]),
 d("LLM Gateway 交付","完善 Gateway 并写文档。",
   ["明确交付标准"],
   ["完善代码","补充 README","记录 curl 示例"],
   ["Gateway≈AI 统一入口"],["达到验收吗？"],["Gateway 交付包"],["可切换 2 模型"],[]),
 d("验收与预习","验收并预习 MCP。",["预习 MCP 规范"],["勾选验收"],["准备好学 MCP 吗？"],["周总结"],["完成验收"],[]),
],
14: [
 d("MCP 协议概述","理解 Server/Client/Tool。",
   ["MCP 官方文档"],
   ["读协议概述","列 MCP 与 REST 差异"],
   ["MCP≈AI 工具调用协议"],["理解正确吗？"],["MCP 概念笔记"],["能解释 MCP"],[]),
 d("现有 MCP Server 源码","读 listTools 与 callTool。",
   ["MCP TypeScript SDK"],
   ["读 mcp-server 一个 Server 的 index.ts","梳理 Tool 注册流程"],
   ["listTools≈OpenAPI 列接口"],["注册流程清晰吗？"],["源码笔记"],["能说明注册流程"],["mcp-server/*/src/index.ts"]),
 d("新增 dev 只读 Tool","实现并测试新 Tool。",
   ["dev 环境安全规范"],
   ["实现 dev 只读查询 Tool","定义 input schema"],
   ["Tool≈带 schema 的函数"],["参数设计合理吗？"],["Tool 源码"],["Tool 可调用"],[]),
 d("Cursor MCP 集成","配置并在 Cursor 中调用。",
   ["Cursor MCP 配置","mcp.config.example.json"],
   ["配置 MCP","在 Cursor 测试调用","排查问题"],
   ["Cursor 集成≈IDE 插件"],["调用成功吗？"],["配置说明"],["Cursor 能调用"],["ai-workspace/mcp.config.example.json"]),
 d("安全规范与类比日","写 MCP 使用规范，完成打卡。",
   ["mcp-routing 安全原则"],
   ["写 dev/测试 only 规范","完成类比打卡"],
   ["禁止生产库≈安全红线"],["规范完整吗？"],["安全规范","类比打卡"],["确认未连生产"],[]),
 d("MCP 交付项目","完成 Tool + 配置文档。",
   ["交付清单"],
   ["完善 Tool","写 MCP 配置文档"],
   ["MCP 交付≈可复用工具"],["达到验收吗？"],["MCP 交付包"],["Cursor 调用成功"],[]),
 d("验收与预习","验收并预习 Agent。",["预习 Function Calling"],["勾选验收"],["准备好做 Agent 吗？"],["周总结"],["完成验收"],[]),
],
15: [
 d("Agent 架构设计","画客服 Agent 架构图。",
   ["OpenAI Function Calling"],
   ["画架构图","写 Agent 循环伪代码"],
   ["Agent 循环≈while+tool_call"],["架构合理吗？"],["架构图"],["能画架构"],[]),
 d("MCP Tool 集成","实现查订单意图与 Tool 调用。",
   ["接入 W14 MCP Tool"],
   ["实现意图识别","调用 MCP 查订单","格式化返回"],
   ["Tool Calling≈LLM 调 API"],["调用链正确吗？"],["集成代码"],["查订单可用"],[]),
 d("System Prompt 工程","编写客服 Agent Prompt。",
   ["Prompt 最佳实践"],
   ["写 System Prompt","约束边界与语气","测试 3 轮对话"],
   ["System Prompt≈全局 middleware 上下文"],["Prompt 够清晰吗？"],["Prompt 文档"],["边界明确"],[]),
 d("多场景路由","实现查商品与 FAQ 兜底。",
   ["意图分类"],
   ["实现 3 种意图路由","测试各场景"],
   ["意图路由≈switch+策略"],["路由准确吗？"],["测试记录"],["3 场景通过"],[]),
 d("错误处理与类比日","加 fallback，完成打卡。",
   ["Tool 失败处理"],
   ["实现 fallback","完成类比打卡"],
   ["fallback≈try/catch 友好提示"],["兜底够吗？"],["fallback 代码"],["失败有友好提示"],[]),
 d("客服 Agent Demo","可演示的 Agent Demo。",
   ["Demo 脚本"],
   ["完善 Demo","写使用文档"],
   ["Demo≈可展示成果"],["可演示吗？"],["Agent Demo"],["3 意图正确"],[]),
 d("验收与预习","验收并预习 LangGraph。",["预习 LangGraph"],["勾选验收"],["准备好学编排吗？"],["周总结"],["完成验收"],[]),
],
16: [
 d("LangGraph 入门","实现 3 步 Agent 工作流。",
   ["LangGraph State/Node/Edge"],
   ["实现 3 步工作流","理解 state 传递"],
   ["LangGraph State≈Redux store"],["工作流正确吗？"],["LangGraph Demo"],["3 步可运行"],[]),
 d("PHP Node 链复习","重读支付 NodeExecutionEngine。",
   ["复习 W7 笔记"],
   ["重读 PayService Node 链","列 Context 字段"],
   ["PHP Node≈同步 middleware 管道"],["Context 变化清楚吗？"],["Context 字段表"],["能列 Context"],["pay-service/common/services/pay/PayService.php"]),
 d("编排模式对比","写两种模式伪代码与异同。",
   ["对比分析"],
   ["写伪代码对比","列 3 处相同与 3 处不同"],
   ["编排≈状态机+节点"],["对比有深度吗？"],["对比文档"],["能说出 3 处异同"],[]),
 d("售后 Node 链","读 3 个售后 Node 并画图。",
   ["售后 nodes 目录"],
   ["读 3 个 Node","画售后申请 Node 链"],
   ["支付 vs 售后 Node 异同"],["链路清晰吗？"],["售后 Node 图"],["能画售后链"],["aftersale-service/common/services/nodes/"]),
 d("阶段总结与类比日","完成编排对比文档与阶段④自评。",
   ["阶段自评"],
   ["完成对比文档","完成类比打卡","阶段④自评"],
   ["阶段复盘"],["达到阶段目标吗？"],["对比文档","阶段总结"],["完成阶段自评"],[]),
 d("编排模式交付","完善 LangGraph Demo 与文档。",
   ["交付标准"],
   ["完善 Demo 与文档"],
   ["交付≈可复现"],["达标吗？"],["编排交付包"],["Demo+文档完成"],[]),
 d("验收与预习","验收并预习 RAG。",["预习 Embeddings"],["勾选验收"],["准备好学 RAG 吗？"],["周总结"],["完成验收"],[]),
],
17: [
 d("Embedding 原理","调用 API 向量化文本。",
   ["OpenAI Embeddings 文档"],
   ["调用 Embedding API","理解向量维度"],
   ["Embedding≈文本→向量"],["理解正确吗？"],["向量化示例"],["能调用 API"],[]),
 d("Chunk 切分策略","实现按标题/段落切分。",
   ["Chunk 最佳实践"],
   ["实现 500-1000 token 切分","测试不同策略"],
   ["Chunk≈split()"],["策略影响召回吗？"],["chunking 代码"],["切分可用"],["ai-lab/rag/chunking.py"]),
 d("向量存储","接入 ChromaDB 或 PGVector。",
   ["向量库文档"],
   ["存储 vector+metadata","实现写入与查询"],
   ["向量库≈similaritySearch"],["metadata 设计合理吗？"],["vector_store 代码"],["能存能查"],[]),
 d("召回测试","索引 10+ 片段并测 Top-K。",
   ["语义搜索"],
   ["索引 10+ 文档","测 5 个问题召回"],
   ["Top-K≈搜索前 K 条"],["召回质量如何？"],["召回测试报告"],["能召回相关段"],[]),
 d("优化与类比日","调 Chunk 策略，完成打卡。",
   ["分析失败 case"],
   ["优化 Chunk","完成类比打卡"],
   ["RAG≈语义搜索+生成"],["优化有效吗？"],["优化记录"],["召回改善"],[]),
 d("RAG 索引项目","完成 indexer 与测试报告。",
   ["交付 indexer"],
   ["完善 indexer","写测试报告"],
   ["indexer≈知识库构建"],["达标吗？"],["indexer 交付"],["10+ 片段索引"],[]),
 d("验收与预习","验收并预习 Hybrid Search。",["预习 BM25"],["勾选验收"],["准备好提升准确率吗？"],["周总结"],["完成验收"],[]),
],
18: [
 d("BM25 关键词检索","实现关键词检索路。",
   ["BM25 原理"],
   ["实现 BM25","对比全文搜索"],
   ["BM25≈关键词匹配"],["实现正确吗？"],["BM25 代码"],["关键词路可用"],[]),
 d("Hybrid Search","合并语义与关键词两路结果。",
   ["混合检索"],
   ["实现 Hybrid Search","调权重"],
   ["Hybrid≈两路合并去重"],["权重合理吗？"],["search 代码"],["混合检索可用"],["ai-lab/rag/search.py"]),
 d("Rerank 精排","对 Top-20 重排序。",
   ["Rerank API"],
   ["接入 Rerank","对比精排前后"],
   ["Rerank≈二次排序"],["提升明显吗？"],["rerank 代码"],["精排可用"],[]),
 d("FAQ Agent","实现检索+生成+引用。",
   ["FAQ 设计"],
   ["实现 FAQ Agent","回答附引用来源"],
   ["FAQ≈搜索+LLM"],["引用准确吗？"],["FAQ Agent"],["回答有引用"],[]),
 d("准确率评估","10 题自测并分析失败 case。",
   ["评估方法"],
   ["准备 10 题","记录准确率","分析失败"],
   ["评估≈QA 测试"],[">70% 吗？"],["评估表"],["准确率>70%"],[]),
 d("FAQ 项目交付","完善 FAQ Agent 与优化笔记。",
   ["交付 FAQ"],
   ["完善 Agent","写优化笔记"],
   ["交付≈可演示 FAQ"],["达标吗？"],["FAQ 交付包"],["FAQ 可问答"],[]),
 d("验收与预习","验收并预习 Memory。",["预习 Session"],["勾选验收"],["准备好学多轮对话吗？"],["周总结"],["完成验收"],[]),
],
19: [
 d("SessionManager 设计","实现 Map 存储会话。",
   ["Session 方案"],
   ["实现 SessionManager","设计 sessionId 规则"],
   ["Session≈Map<id,messages[]>"],["设计合理吗？"],["SessionManager"],["能存会话"],["ai-lab/customer-agent/session.ts"]),
 d("上下文窗口","只保留最近 N 条消息。",
   ["token 限制"],
   ["实现窗口截断","估算 token"],
   ["窗口≈messages.slice(-N)"],["N 如何选？"],["窗口逻辑"],["窗口生效"],[]),
 d("摘要压缩","超长时 LLM 生成 summary。",
   ["摘要策略"],
   ["实现摘要压缩","测试长对话"],
   ["摘要≈压缩历史"],["摘要丢信息吗？"],["摘要逻辑"],["超长可压缩"],[]),
 d("5 轮对话测试","设计并跑通 5 轮连贯对话。",
   ["测试用例"],
   ["设计 5 轮用例","验证第 5 轮引用第 1 轮"],
   ["多轮≈有状态聊天"],["上下文丢了吗？"],["测试记录"],["5 轮不断"],[]),
 d("Memory 文档与类比日","写 Memory 设计文档，完成打卡。",
   ["文档化"],
   ["写 Memory 设计文档","完成类比打卡"],
   ["Memory≈聊天 state"],["文档清晰吗？"],["Memory 文档"],["完成打卡"],[]),
 d("多轮 Demo 交付","5 轮对话 Demo 可演示。",
   ["Demo"],
   ["完善 Demo","录屏或截图"],
   ["Demo≈成果展示"],["可演示吗？"],["多轮 Demo"],["5 轮连贯"],[]),
 d("验收与预习","验收并预习 Multi-Agent。",["预习多 Agent"],["勾选验收"],["准备好学协作吗？"],["周总结"],["完成验收"],[]),
],
20: [
 d("三 Agent 架构","画需求→架构→Review 流水线。",
   ["Multi-Agent 模式"],
   ["画架构图","定义输入输出格式"],
   ["多 Agent≈微服务串行"],["分工清晰吗？"],["架构图"],["架构清晰"],[]),
 d("需求 Agent","一句话→结构化需求。",
   ["需求分析 Prompt"],
   ["写需求 Agent Prompt","测 3 个需求"],
   ["需求 Agent≈PM 角色"],["输出结构化吗？"],["需求 Agent"],["3 例可用"],[]),
 d("架构 Agent","需求→架构建议。",
   ["架构 Prompt"],
   ["写架构 Agent","输出 API/数据流建议"],
   ["架构 Agent≈架构师"],["建议可执行吗？"],["架构 Agent"],["有架构输出"],[]),
 d("Review Agent 串联","输入架构→风险与建议。",
   ["Review Prompt"],
   ["写 Review Agent","串联端到端"],
   ["Review≈Code Review"],["报告完整吗？"],["Pipeline"],["端到端可跑"],[]),
 d("阶段⑤总结","优化错误处理，阶段自评。",
   ["阶段自评"],
   ["优化 Pipeline","阶段⑤自评","完成类比打卡"],
   ["阶段复盘"],["达标吗？"],["阶段总结"],["完成阶段自评"],[]),
 d("Multi-Agent Demo","输入需求输出 Review 报告。",
   ["Demo"],
   ["完善 Demo","准备样例输入输出"],
   ["Demo≈毕业预演"],["报告质量如何？"],["Demo+样例"],["可输出 Review"],[]),
 d("验收与预习","验收并预习毕业 PRD。",["预习 PRD 模板"],["勾选验收"],["准备好写 PRD 吗？"],["周总结"],["完成验收"],[]),
],
21: [
 d("场景调研","列 3 个运营痛点场景。",
   ["运营场景分析"],
   ["列商品查询/订单查询/政策问答场景","写场景清单"],
   ["场景≈用户故事来源"],["场景真实吗？"],["场景清单"],["3 个场景"],[]),
 d("用户故事","US-001 到 US-010。",
   ["用户故事写法"],
   ["写 10 条用户故事","每条带验收标准"],
   ["用户故事≈Jira Story"],["验收可测吗？"],["用户故事"],["10 条完成"],[]),
 d("系统架构图","Vue3+PHP+MCP+RAG 架构。",
   ["架构设计"],
   ["画架构图","确定技术选型"],
   ["架构图≈施工图纸"],["选型合理吗？"],["架构图"],["架构图完成"],[]),
 d("API 契约","定义对话/查询/知识库接口。",
   ["API 设计"],
   ["写 API_CONTRACT v1","定义请求响应字段"],
   ["API 契约≈OpenAPI"],["字段一致吗？"],["API 契约"],["契约 v1 完成"],["graduation-project/docs/API_CONTRACT.md"]),
 d("PRD 定稿","AI Review 后定稿 PRD。",
   ["PRD 评审"],
   ["AI Review PRD","修订并定稿 v1.0"],
   ["PRD≈产品需求文档"],["边界清晰吗？"],["PRD v1.0"],["PRD 定稿"],["graduation-project/docs/PRD.md"]),
 d("PRD 评审项目","自问自答评审会议。",
   ["评审 checklist"],
   ["按 checklist 评审","补充风险与边界"],
   ["评审≈需求门禁"],["可开发吗？"],["评审记录"],["评审通过"],[]),
 d("验收与预习","验收并预习全栈实现。",["预习 Vue3 对话 UI"],["勾选验收"],["准备好编码吗？"],["周总结"],["完成验收"],[]),
],
22: [
 d("Vue3 对话 UI","消息列表+输入+引用来源。",
   ["Vue3 Composition API"],
   ["实现对话 UI 组件","消息气泡与加载态"],
   ["对话 UI≈ChatGPT 界面"],["UX 够吗？"],["前端页面"],["UI 可展示"],["graduation-project/frontend/"]),
 d("PHP 薄 API 层","对话代理接口。",
   ["Yii2 REST"],
   ["实现对话代理 API","统一响应格式"],
   ["薄 API≈BFF 代理"],["响应统一吗？"],["API 代码"],["接口可调"],["graduation-project/api/"]),
 d("MCP 集成","订单/商品查询 Tool。",
   ["MCP 调用"],
   ["接入 MCP dev 工具","实现查询逻辑"],
   ["MCP≈后端工具层"],["调用稳定吗？"],["MCP 集成"],["查询可用"],[]),
 d("RAG 集成","政策问答与引用。",
   ["RAG 接入"],
   ["接入 W17-W18 知识库","回答附引用"],
   ["RAG≈知识库问答"],["引用准确吗？"],["RAG 集成"],["政策可问答"],[]),
 d("联调与类比日","前后端联调，完成打卡。",
   ["联调"],
   ["联调修 bug","完成类比打卡"],
   ["联调≈全栈日常"],["流程通吗？"],["联调记录"],["核心流程通"],[]),
 d("MVP 演示","可演示的运营知识助手 MVP。",
   ["MVP 标准"],
   ["完成问政策→查订单→追问","录 Demo"],
   ["MVP≈最小可交付"],["达标吗？"],["MVP Demo"],["流程可跑通"],[]),
 d("验收与预习","验收并预习平台化。",["预习 Skill 格式"],["勾选验收"],["准备好平台化吗？"],["周总结"],["完成验收"],[]),
],
23: [
 d("Prompt 库","客服/查询/FAQ 三模板。",
   ["Prompt 模板"],
   ["整理 3 个 Prompt","写使用说明"],
   ["Prompt 库≈可复用模板"],["模板够吗？"],["Prompt 库"],["3 个 Prompt"],["graduation-project/prompts/"]),
 d("Skill 编写","参考 skill-library 写 3 个 Skill。",
   ["SKILL.md 格式"],
   ["写 3 个 Skill 文件","可被 Agent 加载"],
   ["Skill≈Agent 操作手册"],["格式对吗？"],["3 个 Skill"],["Skill 完整"],["graduation-project/skills/"]),
 d("Workflow 设计","意图识别→路由 Workflow。",
   ["Workflow 设计"],
   ["画 Workflow 图","实现意图路由"],
   ["Workflow≈路由表+管道"],["路由准吗？"],["Workflow 图"],["路由可用"],[]),
 d("集成测试","多场景测试与修复。",
   ["测试"],
   ["测多场景","记录失败 case","修复"],
   ["集成测试≈E2E"],["覆盖够吗？"],["测试报告"],["主要场景通过"],[]),
 d("优化与类比日","响应速度与错误处理优化。",
   ["性能与容错"],
   ["优化响应","完善错误处理","完成打卡"],
   ["优化≈生产就绪"],["够稳定吗？"],["优化记录"],["错误处理完善"],[]),
 d("平台化交付","Prompt+Skill+Workflow 可复用。",
   ["交付"],
   ["整理交付包","写 Skill 使用文档"],
   ["平台化≈可扩展"],["达标吗？"],["平台化交付"],["3 Skill 可加载"],[]),
 d("验收与预习","验收并预习 Docker 部署。",["预习 Docker Compose"],["勾选验收"],["准备好部署吗？"],["周总结"],["完成验收"],[]),
],
24: [
 d("Docker Compose","编排前端+PHP+向量库。",
   ["Docker Compose 文档"],
   ["写 docker-compose.yml","配置环境变量"],
   ["compose≈一键启动"],["配置正确吗？"],["docker-compose.yml"],["配置完成"],["graduation-project/docker-compose.yml"]),
 d("README 与部署文档","完善启动说明。",
   ["文档规范"],
   ["写 README","写 DEPLOY.md"],
   ["README≈他人上手入口"],["步骤清晰吗？"],["README","DEPLOY.md"],["文档完整"],[]),
 d("Demo 验证","docker compose up 并录 Demo。",
   ["演示"],
   ["验证 compose up","录 Demo 或 GIF"],
   ["Demo≈毕业展示"],["他人能启动吗？"],["Demo 录屏"],["compose 可启动"],[]),
 d("24 周复盘","能力矩阵自评与复盘报告。",
   ["复盘模板"],
   ["填能力矩阵","写 24 周复盘报告"],
   ["复盘≈成长记录"],["短板诚实吗？"],["复盘报告"],["自评完成"],[]),
 d("进阶规划","写 30 周进阶路线。",
   ["进阶方向"],
   ["规划性能/安全/架构/AI 工程化","完成最终类比打卡"],
   ["进阶≈下一阶段地图"],["规划可行吗？"],["进阶计划"],["规划完成"],[]),
 d("毕业交付","整理 Git、文档、Demo 全套交付。",
   ["毕业 checklist"],
   ["整理分支与文档","归档 OpenSpec","确认脱敏"],
   ["毕业≈可展示作品集"],["全套交付吗？"],["毕业交付包"],["可公开上传 GitHub"],[]),
 d("毕业验收","最终验收与庆祝。",
   ["最终验收"],
   ["逐项最终验收","写毕业感言","🎉 毕业"],
   ["毕业≈24 周里程碑"],["全部达标吗？"],["毕业确认"],["完成最终验收"],[]),
],
}.items():
    DETAILED[wk] = dict(days=days)
